# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/aliyun/aliyun-specs.git"

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'AlicloudCrash' , '~> 1.1.0'
  pod 'AlicloudAPM', '~> 1.0.0'
  pod 'AlicloudTLog', '~> 1.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
    config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64 i386'
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
    # config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
   end
  end
 end
